### ISSUE TITLE
Replace moment.js with dayjs

### ISSUE THREAD

**Issue by CVarisco** [dariorinaldi/sortilege#2]
To reduce the library size I suggest to replace moment.js with [dayjs](https://github.com/xx45/dayjs)

**Comment by dariorinaldi** [comment]
Good idea! Thanks for the suggestion

**Comment by Emi-C** [comment]
Unfortunately *moment* is  used to check strict format of datetime values to distinguish them from numbers or numeric strings, but dayjs doesn't allow that (https://github.com/xx45/dayjs#string) vs (https://momentjs.com/docs/#/parsing/string-formats/).

*dayjs* would convert values like "123" to a datetime in milliseconds whatsoever, while *moment* allows us to prevent that, validating just ISO_8601 ND RFC_2822 formats.
